clc;
clear all;
close all;
a=imread('D:\pics\broken.jpg');
subplot(2,2,1);
imshow(a);
title('Original Image');
subplot(2,2,2);
b=rgb2gray(a);
imshow(b);
title('Gray scale Image');
subplot(2,2,4);
c=histeq(a);
imshow(c);
title('Equalized Image');
subplot(2,2,5);
imhist(b);
title('Histogram of gray scale image');
subplot(2,2,6);
imhist(c);
title('Histogram of equalized image');
